on:
  push:
    branches:
      - staging
name: release-production
jobs:
  release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "Version and Release"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          yarn install --frozen-lockfile
          npx lerna version --conventional-commits --conventional-graduate --create-release github --yes --force-git-tag
