on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "Version and Release"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          git checkout staging
          git reset --hard origin/master
          git push --force
          yarn install --frozen-lockfile
          npx lerna version --conventional-commits --conventional-prerelease --preid rc --yes
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          base: production
          branch: staging
          draft: true
          title: 'chore(release): 👾 Merge staging to production'
          body: |
            Update CHANGELOG
            - Updated version ${{ steps.package-version.outputs.current-version}}
            - Auto-generated by [create-pull-request][1]
            
            [1]: https://github.com/peter-evans/create-pull-request
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
