on:
  push:
    branches:
      - master
name: release-please
jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "Version and Release"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          git checkout master
          git checkout -b release--branches--master
          git push --force --set-upstream origin release--branches--master
          yarn install --frozen-lockfile
          npx lerna version --conventional-commits --conventional-prerelease --create-release github --preid rc --force-git-tag --yes
      - name: "Create Pull Request"
        id: cpr
        uses: devops-infra/action-pull-request@v0.5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: release--branches--master
          target_branch: staging
          template: .github/RELEASE_PULL_REQUEST_TEMPLATE.md
          draft: true
      - name: "Check outputs"
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request URL - ${{ steps.cpr.outputs.url }}"
